##docker-compose for server
#version: '3.9'
#services:
#
#  frontend:
#    container_name: frontend
#    image: ghcr.io/24fsiit16/dear-dev-frontend:latest
#    environment:
#      - NEXT_TRUST_HOST=true
#    ports:
#      - "3000:3000"
#
#  db:
#    image: postgres:13
#    container_name: postgres_db
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#  backend:
#    container_name: backend
#    image: ghcr.io/24fsiit16/dear-dev-backend:latest
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#
#  nginx:
#    container_name: nginx
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - frontend
#      - backend
#
#volumes:
#  postgres_data:
