## copy of the docker-compose file on the server
## backend, frontend, db, nginx

#version: '3.9'
#
#services:
#  frontend:
#    container_name: frontend
#    image: ghcr.io/24fsiit16/dear-dev-frontend:latest
#    ports:
#      - "3000:3000"
#    env_file:
#      - .env
#    depends_on:
#      - backend
#
#  yappi_db:
#    image: postgres:13
#    container_name: yappi_db
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    env_file:
#      - .env
#
#  backend:
#    container_name: backend
#    image: ghcr.io/24fsiit16/dear-dev-backend:latest
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env
#    depends_on:
#      - yappi_db
#
#  nginx:
#    container_name: nginx
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - frontend
#      - backend
#
#
#volumes:
#  postgres_data:
#

