version: '3.8'

services:
  yappi-app:
    container_name: yappi_frontend
    image: ghcr.io/24fsiit16/dear-dev-frontend:latest
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    networks:
      - yappi_network

networks:
  yappi_network:
    external: true
